name: mi primer github action
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Saludar
      run: echo Hola cuando hace un push
    - name: docker
      run: docker -v
    - name: build image
      run: docker build . -t dtorres9/gitactnodeimage:240520
    - name: list image
      run: docker images
    - name: running image
      run: docker run -d dtorres9/gitactnodeimage:240520
    - name: listing containers
      run: docker ps -a
      
    
